# Site settings
title: Becca Nelson
email: beccanelsonmakesthings@gmail.com
description: "Thoughts on life, creativity, and technology."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beccanelsonmakesthings.com" # the base hostname & protocol for your site
twitter_username: beccaliz
github_username:  beccanelson
facebook_username: beccanelsonwriter
instagram_username: beccawonders
disqus_username: beccanelsongithub
permalink: /:title

# Build settings
markdown: kramdown
